include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_const: true
    sort_child_properties_last: true

analyzer:
  errors:
    non_constant_identifier_names: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

formatter:
  trailing_commas: preserve